name: Build and Deploy to Docker Hub

on:
  workflow_call: {}

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner != 'brianmay' || github.event_name != 'pull_request' }}

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha, format=long
      - name: BrianMay meta
        id: brianmay_meta
        uses: brianmay/docker-meta@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        if: ${{ github.repository_owner == 'brianmay' && github.ref_name == 'main' && github.event_name != 'pull_request' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.repository_owner == 'brianmay' && github.ref_name == 'main' && github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          cache-to: type=inline
          build-args: ${{ steps.brianmay_meta.outputs.build-args }}
      - name: Notify update
        if: ${{ github.repository_owner == 'brianmay' && github.ref_name == 'main' && github.event_name != 'pull_request' }}
        run: |
          curl -d '{"name": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}", "tag": "main"}'  https://home.linuxpenguins.xyz/v1/webhooks/native
          curl -d '{"name": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}", "tag": "main"}'  https://cloud.linuxpenguins.xyz/v1/webhooks/native
