name: Build and Deploy to Docker Hub

on:
  workflow_call:
      inputs:
        apt_packages:
          description: "Extra apt packages to install"
          required: false
          type: string
          default: ""
        test_data:
          description: "Test data to install"
          required: false
          type: string
          default: ""
        build_npm_assets:
          description: "Build npm assets"
          required: false
          type: boolean
          default: true
        directory:
          description: "Project directory"
          required: false
          type: string
          default: "."
        mix_cache_postfix:
          required: false
          type: string
          default: ""
        plts_cache_postfix:
          required: false
          type: string
          default: ""

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner != 'brianmay' || github.event_name != 'pull_request' }}

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        ports: ["5432:5432"]
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        elixir: [1.13.1]
        otp: [24.2]

    env:
      DATABASE_URL_TEST: postgresql://postgres:postgres@localhost/test?sslmode=disable
      MIX_ENV: test
      BUILD_WITHOUT_QUIC: true

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install system dependancies
        if: ${{ inputs.apt_packages }}
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes ${{ inputs.apt_packages }}
      - name: Setup elixir
        uses: erlef/setup-elixir@v1.10
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2.1.7
        id: mix-cache # id to use in retrieve action
        with:
          path: ${{ inputs.directory }}/deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ inputs.directory }}-mix-${{ hashFiles(format('{0}{1}', inputs.directory, '/mix.lock')) }}${{ inputs.mix_cache_postfix }}
      - name: Install Mix Dependencies
        working-directory: ${{ inputs.directory }}
        if: ${{ steps.mix-cache.outputs.cache-hit != 'true' }}
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Build
        working-directory: ${{ inputs.directory }}
        run: |
          mix compile
      - name: Build NPM assets
        if: ${{ inputs.build_npm_assets }}
        working-directory: ${{ inputs.directory }}
        run: |
          npm install --prefix assets
          npm run deploy --prefix assets
      - name: Check Formatting
        working-directory: ${{ inputs.directory }}
        run: mix format --check-formatted
      - name: Run Credo
        working-directory: ${{ inputs.directory }}
        run: mix credo --strict
      - name: Download and extract test data
        working-directory: ${{ inputs.directory }}
        if: ${{ inputs.test_data }}
        run: |
          wget ${{ inputs.test_data }} -O test_data.tar
          tar -xvf test_data.tar
      - name: Run Tests
        working-directory: ${{ inputs.directory }}
        run: mix test

  dialyzer:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner != 'brianmay' || github.event_name != 'pull_request' }}

    strategy:
      matrix:
        elixir: [1.13.1]
        otp: [24.2]

    env:
      MIX_ENV: test
      BUILD_WITHOUT_QUIC: true

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup elixir
        uses: erlef/setup-elixir@v1.10
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2.1.7
        id: mix-cache # id to use in retrieve action
        with:
          path: ${{ inputs.directory }}/deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ inputs.directory }}-mix-${{ hashFiles(format('{0}{1}', inputs.directory, '/mix.lock')) }}${{ inputs.mix_cache_postfix }}
      - name: Retrieve PLT Cache
        uses: actions/cache@v2.1.7
        id: plt-cache
        with:
          path: ${{ inputs.directory }}/priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ inputs.directory }}-plts-${{ hashFiles(format('{0}{1}', inputs.directory, '/mix.lock')) }}${{ inputs.plts_cache_postfix }}
      - name: Install Mix Dependencies
        working-directory: ${{ inputs.directory }}
        if: ${{ steps.mix-cache.outputs.cache-hit != 'true' }}
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Build
        working-directory: ${{ inputs.directory }}
        run: |
          mix compile
      - name: Create PLTs
        working-directory: ${{ inputs.directory }}
        if: ${{ steps.plt-cache.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt
      - name: Run dialyzer
        working-directory: ${{ inputs.directory }}
        run: mix dialyzer --no-check
